

-- Basic Schema Changes FOR RELATIONSHIPS
ALTER TABLE AOL_SCHEMA.QUERYDIM ADD PRIMARY KEY (ID);
ALTER TABLE AOL_SCHEMA.URLDIM ADD PRIMARY KEY (ID);
ALTER TABLE AOL_SCHEMA.ANONIDDIM ADD PRIMARY KEY (ID);
ALTER TABLE AOL_SCHEMA.TIMEDIM ADD PRIMARY KEY (ID);
ALTER TABLE AOL_SCHEMA.ECOM_EVENTS ADD PRIMARY KEY (EVENT_ID);

-- FOREIGN KEYS
ALTER TABLE AOL_SCHEMA.FACTS
ADD CONSTRAINT fk_facts_anonid
FOREIGN KEY (ANONID) REFERENCES AOL_SCHEMA.ANONIDDIM(ID);

ALTER TABLE AOL_SCHEMA.FACTS
ADD CONSTRAINT fk_facts_queryid
FOREIGN KEY (QUERYID) REFERENCES AOL_SCHEMA.QUERYDIM(ID);

ALTER TABLE AOL_SCHEMA.DIGITAL_QUERY_IDS
ADD CONSTRAINT fk_facts_queryid
FOREIGN KEY (QUERYID) REFERENCES AOL_SCHEMA.QUERYDIM(ID);

ALTER TABLE AOL_SCHEMA.FACTS
ADD CONSTRAINT fk_facts_timeid
FOREIGN KEY (TIMEID) REFERENCES AOL_SCHEMA.TIMEDIM(ID);

ALTER TABLE AOL_SCHEMA.FACTS
ADD CONSTRAINT fk_facts_urlid
FOREIGN KEY  (URLID) REFERENCES AOL_SCHEMA.URLDIM(ID);

ALTER TABLE AOL_SCHEMA.ECOM_EVENT_TIME
ADD CONSTRAINT fk_facts_timeid
FOREIGN KEY  (TIMEID) REFERENCES AOL_SCHEMA.TIMEDIM(ID);

ALTER TABLE AOL_SCHEMA.ECOM_EVENT_TIME
ADD CONSTRAINT fk_facts_timeid
FOREIGN KEY  (TIMEID) REFERENCES AOL_SCHEMA.TIMEDIM(ID);

ALTER TABLE AOL_SCHEMA.ECOM_EVENT_TIME
ADD CONSTRAINT fk_facts_eventid
FOREIGN KEY  (EVENT_ID) REFERENCES AOL_SCHEMA.ECOM_EVENTS(EVENT_ID);




